version: '3.1'
services:
  aidbox-ts-generator:
    image: "bedasoftware/aidbox-ts-generator:latest"
    command: ["-o", "/tmp/aidbox.ts", "-u", "${AIDBOX_URL}", "--user", "$AIDBOX_CLIENT_ID", "--pass", "$AIDBOX_CLIENT_SECRET"]
    links:
      - "devbox:devbox"
    env_file:
      - .env
    volumes:
      - ./shared/src/contrib/aidbox/index.ts:/tmp/aidbox.ts
