version: '3.3'
services:
  dockerize-devbox:
    image: jwilder/dockerize
    command: dockerize -wait http://devbox:8989/__healthcheck -timeout 300s
    depends_on:
      - devbox
    links:
      - devbox
  dockerize-app:
    image: jwilder/dockerize
    command: dockerize -wait http://devbox:8989/app-healthcheck -timeout 300s
    depends_on:
      - devbox
    links:
      - devbox
  app:
    container_name: app-test
    build: 
      context: ./node-app
      dockerfile: Dockerfile.dev
    depends_on:
      - "devbox"
    links:
      - "devbox"
    env_file:
      - .env
    environment:
      AIDBOX_URL: 'http://devbox:8989'
    volumes:
      - ./node-app:/app
    # Colored logs
    tty: true
  devbox:
    image: "${AIDBOX_IMAGE}"
    container_name: devbox-test
    depends_on:
      - "devbox-db"
    links:
      - "devbox-db:database"
    ports:
      - "8989:8989"
    env_file:
      - .env
    environment:
      PGHOST: database
      AIDBOX_PORT: 8989
      AIDBOX_URL: 'http://devbox:8989'
#    extra_hosts:
#      - "host.docker.internal:host-gateway"

  devbox-db:
    image: "${PGIMAGE}"
    container_name: devbox-db-test
    environment:
      POSTGRES_USER:     "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_DB:       "${PGDATABASE}"
